[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | frontend
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
[tool.pytest.ini_options]
testpaths = ["tests"]  # Ensure this points to your test folder
python_files = ["test_*.py", "*_test.py"]  # Recognize test files
python_classes = ["Test*"]  # Recognize test classes
python_functions = ["test_*"]  # Recognize test functions